package scenariocontext;

public enum ScenarioContextKey {
    USERNAME,
    PASSWORD,
    FIRSTNAMEPERSONALPAGE,
    LASTNAMEPERSONALPAGE,
    EMAILPERSONALPAGE,
    USERNAMEPERSONALPAGE,

    FIRSTNAME_MYPROFILE,
    LASTNAME_MYPROFILE,
    USERNAME_MYPROFILE,
    EMAIL_MYPROFILE,
    PASSWORD_MYPROFILE
}